input {
  beats {
    port => 5401
  }
}

filter {
  # Проверяем, что это логи mysql (если настроено в Filebeat)
  # или просто обрабатываем многострочные логи медленных запросов
  grok {
    match => { "message" => "(?m)^# User@Host: %{USER:user}\[[^\]]+\] @ %{HOSTNAME:clienthost} \[[^\]]*\]\s+Id:\s+%{NUMBER:thread_id:int}\s+# Query_time: %{NUMBER:query_time:float}\s+Lock_time: %{NUMBER:lock_time:float}\s+Rows_sent: %{NUMBER:rows_sent:int}\s+Rows_examined: %{NUMBER:rows_examined:int}\s*(?:use %{DATA:database};\s*)?SET timestamp=%{NUMBER:timestamp_unix:int};\s*(?<query>(?<=\n)(?s).*)" }
  }

  # Превращаем Unix-timestamp из лога MySQL в официальное время события @timestamp
  date {
    match => [ "timestamp_unix", "UNIX" ]
    remove_field => [ "timestamp_unix" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "mysql-slow-%{+YYYY.MM.dd}" # Отдельный индекс для удобного поиска
  }
  stdout { codec => rubydebug }
}

